package top.putop.mi.db.model;

public class VedioMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio_message.id
     *
     * @mbg.generated Tue May 08 14:13:29 AWST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio_message.vedio_name
     *
     * @mbg.generated Tue May 08 14:13:29 AWST 2018
     */
    private String vedioName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio_message.vedio_img_url
     *
     * @mbg.generated Tue May 08 14:13:29 AWST 2018
     */
    private String vedioImgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio_message.vedio_type
     *
     * @mbg.generated Tue May 08 14:13:29 AWST 2018
     */
    private String vedioType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio_message.vedio_url
     *
     * @mbg.generated Tue May 08 14:13:29 AWST 2018
     */
    private String vedioUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio_message.id
     *
     * @return the value of vedio_message.id
     *
     * @mbg.generated Tue May 08 14:13:29 AWST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio_message.id
     *
     * @param id the value for vedio_message.id
     *
     * @mbg.generated Tue May 08 14:13:29 AWST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio_message.vedio_name
     *
     * @return the value of vedio_message.vedio_name
     *
     * @mbg.generated Tue May 08 14:13:29 AWST 2018
     */
    public String getVedioName() {
        return vedioName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio_message.vedio_name
     *
     * @param vedioName the value for vedio_message.vedio_name
     *
     * @mbg.generated Tue May 08 14:13:29 AWST 2018
     */
    public void setVedioName(String vedioName) {
        this.vedioName = vedioName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio_message.vedio_img_url
     *
     * @return the value of vedio_message.vedio_img_url
     *
     * @mbg.generated Tue May 08 14:13:29 AWST 2018
     */
    public String getVedioImgUrl() {
        return vedioImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio_message.vedio_img_url
     *
     * @param vedioImgUrl the value for vedio_message.vedio_img_url
     *
     * @mbg.generated Tue May 08 14:13:29 AWST 2018
     */
    public void setVedioImgUrl(String vedioImgUrl) {
        this.vedioImgUrl = vedioImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio_message.vedio_type
     *
     * @return the value of vedio_message.vedio_type
     *
     * @mbg.generated Tue May 08 14:13:29 AWST 2018
     */
    public String getVedioType() {
        return vedioType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio_message.vedio_type
     *
     * @param vedioType the value for vedio_message.vedio_type
     *
     * @mbg.generated Tue May 08 14:13:29 AWST 2018
     */
    public void setVedioType(String vedioType) {
        this.vedioType = vedioType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio_message.vedio_url
     *
     * @return the value of vedio_message.vedio_url
     *
     * @mbg.generated Tue May 08 14:13:29 AWST 2018
     */
    public String getVedioUrl() {
        return vedioUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio_message.vedio_url
     *
     * @param vedioUrl the value for vedio_message.vedio_url
     *
     * @mbg.generated Tue May 08 14:13:29 AWST 2018
     */
    public void setVedioUrl(String vedioUrl) {
        this.vedioUrl = vedioUrl;
    }
}