package top.putop.mi.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import top.putop.mi.db.model.VedioMessage;

@Mapper
public interface VedioMessageMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table vedio_message
	 *
	 * @mbg.generated Tue May 08 14:13:29 AWST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table vedio_message
	 *
	 * @mbg.generated Tue May 08 14:13:29 AWST 2018
	 */
	int insert(VedioMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table vedio_message
	 *
	 * @mbg.generated Tue May 08 14:13:29 AWST 2018
	 */
	int insertSelective(VedioMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table vedio_message
	 *
	 * @mbg.generated Tue May 08 14:13:29 AWST 2018
	 */
	VedioMessage selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table vedio_message
	 *
	 * @mbg.generated Tue May 08 14:13:29 AWST 2018
	 */
	int updateByPrimaryKeySelective(VedioMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table vedio_message
	 *
	 * @mbg.generated Tue May 08 14:13:29 AWST 2018
	 */
	int updateByPrimaryKey(VedioMessage record);

	/**
	 * 获取数据信息
	 * 
	 * @return
	 */
	List<VedioMessage> getAllMess(@Param(value = "vedioName") String vedioName,
			@Param(value = "vedioType") String vedioType, @Param(value = "beforeNum") Integer beforeNum,
			@Param(value = "limitNum") Integer limitNum);

	/**
	 * 获取总数
	 * 
	 * @return
	 */
	int selectCount();
}